version: "3.7"

services:
  laravel:
    build:
      context: .
    container_name: $COMPOSE_PROJECT_NAME-laravel
    environment:
      DB_DATABASE: laravel
      DB_HOST: mysql
      DB_PASSWORD: secret
      DB_USERNAME: laravel
      APP_DEBUG: 'false'
      APP_ENV: local
      APP_KEY: ayGbuqVXJakHHvMTZCjKqzhVqMNsHMQs
      LOG_CHANNEL: stderr
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html
    command: sh -c "php artisan migrate --force && apache2-foreground"
    networks:
      - app

  mysql:
    image: mysql:8
    container_name: $COMPOSE_PROJECT_NAME-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - app

networks:
  app:
    driver: bridge